### ISSUE TITLE
sshfs host path expand  error

### ISSUE THREAD

**Issue by shuxiao9058** [dustymabe/vagrant-sshfs#82] opened 2017-08-09 15:37 UTC
```
config.vm.synced_folder "~/", "/home/vagrant/web",
                            type: "sshfs", 
                            ssh_host: "develop-host", ssh_username: "user", ssh_port: "22",
                            ssh_opts_append: "-o Compression=yes -o CompressionLevel=5",
                            sshfs_opts_append: "-o cache=no",
                            disabled: false
```

expand command as: 
```
sshfs -p 22  -o StrictHostKeyChecking=no  -o ServerAliveInterval=30  -o Compression=yes -o CompressionLevel=5  -o allow_other  -o noauto_cache  -o cache=no -o cache_timeout=115200 user@develop-host:'/Users/user' /home/vagrant/web
```

the host path is /Users/user, but I want the path is `/home/user` on linux.

While the path is /data/web, it report an error:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: /data/web
```

**Comment by dustymabe** [comment] 2018-02-12 02:09
so you are doing arbitrary host mounting of an ssh folder. Can you try running this with `vagrant up` and also with `vagrant sshfs` and tell me if you get the same results.

Basically we've seen behavior where the home directory expansion gets expanded a different way depending on if you are going through the `vagrant up` path vs the `vagrant sshfs` path. See this comment for more information: https://github.com/dustymabe/vagrant-sshfs/issues/59#issuecomment-263681746. I suspect this is a duplicate of #59.

**Closed** 2018-03-11 20:51 UTC
