### ISSUE TITLE
Multiple machines mounts lost when new machine started up

### ISSUE THREAD

**Issue by mitchellmaler** [dustymabe/vagrant-sshfs#106] opened 2019-10-16 22:09 UTC
I have a Vagrantfile that launches multiple machines which are all mounting the /vagrant directory and the first machine is mounting a second mount. When I start the first machine both mounts are working fine. When the next machine boots up it stops those two ssh mounts and then mounts the single one to the new machine. I was expecting all ssh clients to stay open and keep all machine mounts until the machine is halted/suspended or destroyed.

**Comment by dustymabe** [comment] 2019-10-17 00:51
- What platform are you on and what OS is your vagrant instance?
- Do you have an example Vagrantfile

**Comment by mitchellmaler** [comment] 2019-10-17 02:50
@dustymabe I am running on MacOS 10.14.6 (18G103
vagrant-sshfs (1.3.1, global)
Vagrant Version: 2.2.5
Using the vmware_desktop provider: Version 11.5.0
SSH Version: OpenSSH_7.9p1, LibreSSL 2.7.3

## Vagrant File

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "VM1" do |vm1|
    vm1.vm.hostname = "VM1"
    vm1.vm.box = "generic/centos7"

    vm1.vm.provider "vmware_desktop" do |vm|
      vm.memory = "1024"
      vm.cpus   = "1"
    end

    vm1.vm.synced_folder ".", "/vagrant", type: "sshfs"
  end

  config.vm.define "VM2" do |vm2|
    vm2.vm.hostname = "VM2"
    vm2.vm.box = "generic/centos7"

    vm2.vm.provider "vmware_desktop" do |vm|
      vm.memory = "1024"
      vm.cpus   = "1"
    end

    vm2.vm.synced_folder ".", "/vagrant", type: "sshfs"
  end
end
```

## Startup Log

```
$ vagrant up
Bringing machine 'VM1' up with 'vmware_desktop' provider...
Bringing machine 'VM2' up with 'vmware_desktop' provider...
==> VM1: Cloning VMware VM: 'generic/centos7'. This can take some time...
==> VM1: Checking if box 'generic/centos7' version '1.9.36' is up to date...
==> VM1: Verifying vmnet devices are healthy...
==> VM1: Preparing network adapters...
==> VM1: Fixed port collision for 22 => 2222. Now on port 2200.
==> VM1: Starting the VMware VM...
==> VM1: Waiting for the VM to receive an address...
==> VM1: Forwarding ports...
    VM1: -- 22 => 2200
==> VM1: Waiting for machine to boot. This may take a few minutes...
    VM1: SSH address: 127.0.0.1:2200
    VM1: SSH username: vagrant
    VM1: SSH auth method: private key
    VM1: 
    VM1: Vagrant insecure key detected. Vagrant will automatically replace
    VM1: this with a newly generated keypair for better security.
    VM1: 
    VM1: Inserting generated public key within guest...
    VM1: Removing insecure key from the guest if it's present...
    VM1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> VM1: Machine booted and ready!
==> VM1: Setting hostname...
==> VM1: Configuring network adapters within the VM...
==> VM1: Installing SSHFS client...
==> VM1: Mounting SSHFS shared folder...
==> VM1: Mounting folder via SSHFS: /Users/mitch.maler/Desktop/test => /vagrant
==> VM1: Checking Mount..
==> VM1: Folder Successfully Mounted!
==> VM2: Cloning VMware VM: 'generic/centos7'. This can take some time...
==> VM2: Checking if box 'generic/centos7' version '1.9.36' is up to date...
==> VM2: Verifying vmnet devices are healthy...
==> VM2: Preparing network adapters...
==> VM2: Fixed port collision for 22 => 2222. Now on port 2201.
==> VM2: Starting the VMware VM...
==> VM2: Waiting for the VM to receive an address...
==> VM2: Forwarding ports...
    VM2: -- 22 => 2201
==> VM2: Waiting for machine to boot. This may take a few minutes...
    VM2: SSH address: 127.0.0.1:2201
    VM2: SSH username: vagrant
    VM2: SSH auth method: private key
    VM2: 
    VM2: Vagrant insecure key detected. Vagrant will automatically replace
    VM2: this with a newly generated keypair for better security.
    VM2: 
    VM2: Inserting generated public key within guest...
    VM2: Removing insecure key from the guest if it's present...
    VM2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> VM2: Machine booted and ready!
==> VM2: Setting hostname...
==> VM2: Configuring network adapters within the VM...
==> VM2: Installing SSHFS client...
==> VM2: Mounting SSHFS shared folder...
==> VM2: Mounting folder via SSHFS: /Users/mitch.maler/Desktop/test => /vagrant
==> VM2: Checking Mount..
==> VM2: Folder Successfully Mounted!
```
## showing one vm doesn't have the mounted files anymore

```
bash-5.0$ vagrant ssh VM1
Last login: Thu Oct 17 02:48:30 2019 from 192.169.152.2
[vagrant@VM1 ~]$ ls -l /vagrant
total 0
[vagrant@VM1 ~]$ exit
logout
Connection to 127.0.0.1 closed.
bash-5.0$ vagrant ssh VM2
[vagrant@VM2 ~]$ ls -l /vagrant
total 8
drwxr-xr-x. 1 502 games  96 Oct 17 02:36 test
-rw-r--r--. 1 502 games 604 Oct 17 02:43 Vagrantfile
[vagrant@VM2 ~]$ exit
logout
Connection to 127.0.0.1 closed.
```

## ssh sshfs processes running after startup
```
$ ps -ef | grep sshfs | grep -v grep
  502 99529     1   0  9:45PM ttys004    0:00.03 /usr/bin/ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o User=vagrant -o Port=2201 -o UserKnownHostsFile=/dev/null -F /dev/null -o IdentityFile="/Users/mitch.maler/Desktop/test/.vagrant/machines/VM2/vmware_desktop/private_key" 127.0.0.1 sudo -E sshfs :/Users/mitch.maler/Desktop/test /vagrant -o allow_other  -o noauto_cache  -o slave  
```

**Comment by dustymabe** [comment] 2019-10-17 16:12
I couldn't get `generic/centos7` to boot but I can using the [official centos/7 box](https://app.vagrantup.com/centos/boxes/7). However, I can't reproduce the reported problem in my environment (Fedora Linux using libvirt):

```
$ vagrant ssh VM1 -- /usr/bin/md5sum /vagrant/Vagrantfile
fded0ef9275d7db34726a31ca003b08d  /vagrant/Vagrantfile
$ vagrant ssh VM2 -- /usr/bin/md5sum /vagrant/Vagrantfile
fded0ef9275d7db34726a31ca003b08d  /vagrant/Vagrantfile
```

Maybe it's something specific to MacOS?

After the machines are up if you run `vagrant sshfs --unmount && vagrant sshfs --mount` does the problem still exist? If so then maybe run `vagrant sshfs --unmount && vagrant sshfs --mount &> /tmp/output.txt` and share the output so we can see if there are any smoking guns. Unfortunately I don't have a system with MacOS that I can test this on.

**Comment by dustymabe** [comment] 2022-06-10 19:12
Closing this. Please re-open if there is new information to add or the problem persists.

**Closed by dustymabe** 2022-06-10 19:12 UTC
