### ISSUE TITLE
mount point is read only

### ISSUE THREAD

**Issue by jjn1056** [dustymabe/vagrant-sshfs#60] opened 2016-12-03 02:29 UTC
Hi,

I've been trying to upgrade my configuration from the old (but working) plugin to this one.  There's a host of problems but the most serious one is when I mount the guest folder onto my desktop (I'm on a Mac) everything is read only.  There's some difference in the options I guess between your new plugin and the old one that worked but I can't figure it out from looking over the source.  Here's the code section:

  if Vagrant.has_plugin?("vagrant-sshfs") && ENV['SSHFS_MOUNT_POINT_HOST'] && ENV['SSHFS_MOUNT_POINT_GUEST']
    config.vm.synced_folder ENV['SSHFS_MOUNT_POINT_HOST'], ENV['SSHFS_MOUNT_POINT_GUEST'],
      ssh_username: "dev",
      disabled: false, type: "sshfs",
      reverse: true
  end

I can mount but it s read only and none of the normal options to address this (-o allow_other,default_permissions) seems to help.  

Been struggling with this fora few days (I have dozens of vagrant files with the old plugin that are now all busted).  Really on the verge of just forking the old one.

Other problems include the fact that the build in rsync folder sync doesn't get disabled and I seem to get cases where the process that created this gets held open and I have to reboot.  But lets figure out this read only thing, it must be something small.  The only thing I can see difference between your version and the old working one is you added 

 -F /dev/null

https://github.com/dustymabe/vagrant-sshfs/blob/master/lib/vagrant-sshfs/cap/host/darwin/sshfs_reverse_mount.rb#L76

not sure if that is enough to mount read only though.

Any chance of you releasing the old working plugin under this namespace and putting your new one under a different namespace?  Really this is likely busting code all over the place.

**Comment by dustymabe** [comment] 2016-12-03 16:17
hey @jjn1056, thanks for the report. I haven't experienced this problem (read-only mounting), but would like to get it fixed for you. I don't have access to a mac system right now but I should be able to ask around and get access to one next week to try to reproduce. 

Is the vagrant box you are using one that is publicly accessible? When I try to repro I'd like to use the same one.

**Comment by jjn1056** [comment] 2016-12-03 22:49
Hey @dustymabe 

OK so I do have a mac :)  And here is what I found.  If I specify the ssh_username in my Vagrantfile, it gets ignored.  So for example here is the config

    config.vm.synced_folder ENV['SSHFS_MOUNT_POINT_HOST'], ENV['SSHFS_MOUNT_POINT_GUEST'],
      ssh_username: "dev",
      disabled: false, type: "sshfs",
      reverse: true

BUT when I do VAGRANT_LOG=debug and I find the actually sshfs command that the plugin issues I get this:

/usr/local/bin/sshfs  -o StrictHostKeyChecking=no  -o ServerAliveInterval=30  -o Port=2354 -o "IdentityFile=\"/Users/jnapiorkowski/.vagrant.d/insecure_private_key\"" -o UserKnownHostsFile=/dev/null  -F /dev/null    -o noauto_cache   vagrant@127.0.0.1:/home/dev/src/adama /Users/jnapiorkowski/src

Note the "vagrant@127.0.0.1"... bit?  So for my use case the code is running under a user 'dev' not vagrant so that option is actually needed for me.  

So at least that much I can see.   Looks like compared to the original plugin you have a lot more options in the mix.  I'll mess around with it on the command line and see if I can find a permutation that actually works.  But I can see at the very least that ssh_username is getting ignored.

**Comment by jjn1056** [comment] 2016-12-03 23:19
@dustymabe OK so FWIW if I go to the command line and issue the command annual but I fix the ssh_username it seems to work.  So I think if we can just fix this so that the ssh_username setting is respected that should fix the problem for me.  I don't know ruby that well, but if you can give me a pointer I'll try to get you a PR.  I told my CTO i'd have this fixed by Monday, even if I have to fork the code, since it basically killed our deploy to QA on Thursday.

**Comment by jjn1056** [comment] 2016-12-03 23:27
@dustymabe 

So to be clear when I run this from the CLI:

/usr/local/bin/sshfs -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o Port=2354 -o "IdentityFile="/Users/jnapiorkowski/.vagrant.d/insecure_private_key"" -o UserKnownHostsFile=/dev/null -F /dev/null -o noauto_cache vagrant@127.0.0.1:/home/dev/src/adama /Users/jnapiorkowski/src

I get a mount but because the user is wrong (vagrant not dev) the files are readonly.  If I unmount that and then run this command:

/usr/local/bin/sshfs -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o Port=2354 -o "IdentityFile="/Users/jnapiorkowski/.vagrant.d/insecure_private_key"" -o UserKnownHostsFile=/dev/null -F /dev/null -o noauto_cache dev@127.0.0.1:/home/dev/src/adama /Users/jnapiorkowski/src

It seems to be fine (although I'm testing but I think its a pretty simple issue)

So I think all we need to do is figure out why if I set ssh_username it gets ignored.  Like I said, not a rubist but when I look at 

https://github.com/dustymabe/vagrant-sshfs/blob/master/lib/vagrant-sshfs/cap/host/darwin/sshfs_reverse_mount.rb#L84

Looks to me like username is getting from machine not opts, maybe we want something like username =  opts[:ssh_username] ? opts[:ssh_username] : machine[:username]  

(sorry not sure if that is the correct ruby syntax...  But it seems to be we want some sort of conditional merge here.

**Comment by jjn1056** [comment] 2016-12-04 01:12
@dustymabe 

Ok so just for fun if I modify this line

https://github.com/dustymabe/vagrant-sshfs/blob/master/lib/vagrant-sshfs/cap/host/darwin/sshfs_reverse_mount.rb#L84

which is

 username = machine.ssh_info[:username]

to be

username = opts[:username]

the command for sshfs is correct in the debug log is right now and everything just works perfectly.  I'll try to work up a PR, but I imagine its basically 

If opts[:ssh_username] exists then use that, if not use machine.ssh_info[:username]

Let me know if that seems right to you.

**Comment by dustymabe** [comment] 2016-12-04 19:38
hey @jjn1056, thanks for the deep investigation on this. I'm in the midst of travel this weekend so I haven't been at the computer or had a chance to think about this very much. 

For the reverse mounting vagrant-sshfs just "re-uses" the information that vagrant already has in order to make the connection with the machine. i.e. it uses the same information that is used when you `vagrant ssh`. If you want to mount as the "dev" user a workaround could be to set `config.ssh.username = 'dev'` in your Vagrantfile.

I'll try to digest the rest of what you have found soon.

**Comment by jjn1056** [comment] 2016-12-04 22:07
I'll give that a try and let y ou know

**Comment by jjn1056** [comment] 2016-12-05 00:40
@dustymabe 

hey so adding "config.ssh.username = 'dev'" does seem to work fine.  I'm not sure how that setting might impact other aspects of the build.  This setup was written by a 'devops expect' who consulted for the company a few months three years ago and he did some old things I don't see in a lot of the examples I come across (like for example creating  dev user for running the application code over vagrant).  I'll let you know if this causes me any trouble during my full builds on monday.  Think over how you might want to proceed, if you think there should be some sort of control over the ssh user independent from the machine I can try to give you a patch for it (code or docs depending on the route you take).

You said you don't have access to a Mac, which I do.  Feel free to toss Mac related debugging stuff at me.  It would give me an excuse to make my boss pay me to learn Ruby ;)

**Comment by dustymabe** [comment] 2017-05-29 21:23
@jjn1056 - how do you think we should proceed on this one?

**Comment by dustymabe** [comment] 2018-02-11 23:56
Since we are just re-using the user that `vagrant ssh` is using to connect to the machine and that seems to work for you I think we'll close this out. I'd prefer not to add another option for setting up a different user to connect with. I will point out that if you really did want to use a different user then you could probably add `ssh_opts_append: -o User=dev' and do it that way.

**Closed by dustymabe** 2018-02-11 23:56 UTC
