### ISSUE TITLE
SSHFS mount failed with CentOS 7 Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [dustymabe/vagrant-sshfs#26] opened 2016-05-23 06:37 UTC
Steps to reproduce
* mkdir centos;cd centos
* vagrant init centos/7
* edit the Vagrantfile to add ` config.vm.synced_folder "./", "/home/vagrant", type: "sshfs"`
* vagrant up

```{r}
[lmohanty@LalatenduM-laptop centos]$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/lmohanty/vagrantboxes/centos/ => /home/vagrant/sync
==> default: Installing SSHFS client...
==> default: Mounting SSHFS shared folders...
==> default: Mounting folder via SSHFS: /home/lmohanty/vagrantboxes/centos => /home/vagrant
==> default: Checking Mount..
Warning: Permanently added '192.168.121.191' (ECDSA) to the list of known hosts.
vagrant@192.168.121.191's password: ==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..

Mounting SSHFS shared via slave SSHFS mount failed. Please look at your 
terminal scrollback to look for any error messages from the processes that 
were run.

```
* `vagrant ssh` asking password to login in to the box
```
[lmohanty@LalatenduM-laptop centos]$ vagrant ssh
vagrant@192.168.121.191's password: 

```
I tried to use the ssh-key from `vagrant ssh`. It did not work and asked for password.

```
[lmohanty@LalatenduM-laptop centos]$ vagrant ssh-config 
Host default
  HostName 192.168.121.191
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile "/home/lmohanty/vagrantboxes/centos/.vagrant/machines/default/libvirt/private_key"
  IdentitiesOnly yes
  LogLevel FATAL

[lmohanty@LalatenduM-laptop centos]$ ssh -i /home/lmohanty/vagrantboxes/centos/.vagrant/machines/default/libvirt/private_key vagrant@192.168.121.191
Warning: Permanently added '192.168.121.191' (ECDSA) to the list of known hosts.
vagrant@192.168.121.191's password: 
Last login: Mon May 23 02:27:36 2016 from 192.168.121.1
```

Cross checked and found that fuse-sshfs is getting installed properly in the guest box. 
```
[vagrant@localhost ~]$ sudo rpm -qa | grep fuse
fuse-libs-2.9.2-6.el7.x86_64
fuse-sshfs-2.5-1.el7.x86_64
fuse-2.9.2-6.el7.x86_64
```

**Comment by LalatenduMohanty** [comment] 2016-05-23 06:42
I have the latest vagrant installed

```
$ vagrant plugin list
fog-libvirt (0.0.3)
  - Version Constraint: 0.0.3
sahara (0.0.17)
vagrant-digitalocean (0.9.0)
vagrant-hosts (2.8.0)
vagrant-libvirt (0.0.33, system)
vagrant-registration (1.2.1)
vagrant-service-manager (1.0.2)
vagrant-sshfs (1.1.0)
```

**Comment by dustymabe** [comment] 2016-06-01 13:15
hey @LalatenduMohanty - what OS is your host machine?

**Comment by LalatenduMohanty** [comment] 2016-06-01 13:26
@dustymabe it is CentOS. I spent some time understanding the issue. I need little more time and will get back to you.

**Comment by LalatenduMohanty** [comment] 2016-06-01 13:29
Forgot to mention ADB/CDK does not have the issue.

**Comment by dustymabe** [comment] 2016-06-02 03:20
I just tried bringing up centos/7 on my f22 host with vagrant-sshfs and it seems to work fine with centos/7 `1602.02`

**Comment by dustymabe** [comment] 2016-06-08 13:19
@LalatenduMohanty - any more information to report on this?

**Comment by dustymabe** [comment] 2016-07-19 16:20
hey @LalatenduMohanty - can you add more information or close this issue if you can't reproduce.

**Comment by dustymabe** [comment] 2016-07-20 19:46
Closing this. Feel free to re-open if the issue presents itself again and you have more information.

**Closed by dustymabe** 2016-07-20 19:46 UTC
